# Generated by Django 5.2.4 on 2025-07-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_reading_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sticky',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
