# Generated by Django 5.2.4 on 2025-07-22 19:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_comment_posts_comme_post_id_7929fe_idx_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='comment',
            new_name='comment_post_recent',
            old_name='posts_comme_post_id_7929fe_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comment_author_recent',
            old_name='posts_comme_author__85ae26_idx',
        ),
        migrations.RenameIndex(
            model_name='comment',
            new_name='comment_active',
            old_name='posts_comme_active_77e66b_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='post_status_created',
            old_name='posts_post_status_9b2301_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='post_author_status',
            old_name='posts_post_author__216072_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='post_slug_unique',
            old_name='posts_post_slug_59b922_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='post_views_desc',
            old_name='posts_post_views_0b07be_idx',
        ),
        migrations.RenameIndex(
            model_name='post',
            new_name='post_sticky_recent',
            old_name='posts_post_is_stic_e68d81_idx',
        ),
        migrations.AddField(
            model_name='post',
            name='cached_comments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de comentarios en caché'),
        ),
        migrations.AddField(
            model_name='post',
            name='cached_likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Contador de likes en caché'),
        ),
        migrations.AddField(
            model_name='post',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actividad'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['active', 'post'], name='comment_active_post'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['active', '-created_at'], name='comment_active_recent'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'active', '-created_at'], name='comment_post_active_recent'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['author', 'active'], name='comment_author_active'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-views', 'status'], name='post_popular_published'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_sticky', 'status', '-created_at'], name='post_sticky_published'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'author', '-created_at'], name='post_author_published'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['created_at'], name='post_created_at'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['reading_time'], name='post_reading_time'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', '-reading_time'], name='post_by_reading_time'),
        ),
    ]
