# Generated by Django 5.2.4 on 2025-07-23 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_rename_posts_comme_post_id_7929fe_idx_comment_post_recent_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIPromptTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Template')),
                ('prompt_type', models.CharField(choices=[('content', 'Generación de Contenido'), ('tags', 'Generación de Tags'), ('image', 'Generación de Imagen')], max_length=20, verbose_name='Tipo de Prompt')),
                ('template', models.TextField(verbose_name='Template del Prompt')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_default', models.BooleanField(default=False, verbose_name='Por Defecto')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Template de Prompt de IA',
                'verbose_name_plural': 'Templates de Prompts de IA',
                'indexes': [models.Index(fields=['prompt_type', 'is_default'], name='prompt_type_default'), models.Index(fields=['is_active'], name='prompt_active')],
                'unique_together': {('name', 'prompt_type')},
            },
        ),
    ]
