services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    restart: unless-stopped

  web:
    build: .
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - media_files:/app/media
      - static_files:/app/staticfiles
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py initialize_tag_system --calculate-cooccurrence --create-history &&
             gunicorn blog.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  celery:
    build: .
    volumes:
      - .:/app
      - media_files:/app/media
    env_file:
      - .env
    depends_on:
      - db
      - redis
    restart: unless-stopped
    command: celery -A blog worker -l info

volumes:
  postgres_data:
  redis_data:
  media_files:
  static_files: