version: '3.8'

services:
  # Base de datos PostgreSQL para desarrollo
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: devblog_dev
      POSTGRES_USER: devblog_user
      POSTGRES_PASSWORD: devblog_password
    ports:
      - "5432:5432"

  # Redis para desarrollo
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  # Aplicación Django en modo desarrollo
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - USE_POSTGRESQL=True
      - POSTGRES_DB=devblog_dev
      - POSTGRES_USER=devblog_user
      - POSTGRES_PASSWORD=devblog_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

volumes:
  postgres_data_dev: