version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: devblog
      POSTGRES_USER: devblog_user
      POSTGRES_PASSWORD: devblog_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devblog_user -d devblog"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - media_files:/app/media
      - static_files:/app/staticfiles
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py initialize_tag_system --calculate-cooccurrence --create-history &&
             gunicorn blog.wsgi:application --bind 0.0.0.0:8000 --workers 3"

  celery:
    build: .
    volumes:
      - .:/app
      - media_files:/app/media
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A blog worker -l info

  celery-beat:
    build: .
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    command: celery -A blog beat -l info

  flower:
    build: .
    ports:
      - "5555:5555"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=production
    env_file:
      - .env.docker
    depends_on:
      - redis
    command: celery -A blog flower --port=5555

volumes:
  postgres_data:
  redis_data:
  media_files:
  static_files: