services:
  # Base de datos PostgreSQL
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5433:5432"
    restart: unless-stopped

  # Aplicación Django
  web:
    build: .
    command: >
      sh -c "echo 'Esperando base de datos...' &&
             sleep 15 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             echo 'Iniciando servidor en puerto 8000...' &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - USE_POSTGRESQL=True
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - ALLOWED_HOSTS=127.0.0.1,localhost,proyecto.skulll.site,172.67.207.165,104.21.85.164
      - USE_X_FORWARDED_HOST=True
      - SECURE_PROXY_SSL_HEADER=HTTP_X_FORWARDED_PROTO,https
    depends_on:
      - db
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume: