# Generated by Django 5.2.4 on 2025-07-11 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_follows_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_post',
            field=models.BooleanField(default=False, verbose_name='Puede crear posts'),
        ),
    ]
