# Generated by Django 5.2.4 on 2025-07-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_can_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_post',
        ),
        migrations.AddField(
            model_name='profile',
            name='permission_requested',
            field=models.BooleanField(default=False, verbose_name='Permiso solicitado'),
        ),
    ]
