# Generated by Django 5.2.4 on 2025-07-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_can_post_profile_permission_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_post',
            field=models.BooleanField(default=False, verbose_name='Puede postear'),
        ),
    ]
