# Generated by Django 5.2.4 on 2025-07-22 02:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_can_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', '-created_at'], name='accounts_no_recipie_799191_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['sender', '-created_at'], name='accounts_no_sender__aa6bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['user'], name='accounts_pr_user_id_97e401_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['can_post'], name='accounts_pr_can_pos_58a68b_idx'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['permission_requested'], name='accounts_pr_permiss_a6acd6_idx'),
        ),
    ]
