# Generated by Django 5.2.4 on 2025-07-22 21:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification_accounts_no_recipie_799191_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_recipient_recent',
            old_name='accounts_no_recipie_799191_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_recipient_read',
            old_name='accounts_no_recipie_8b48cc_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notif_sender_recent',
            old_name='accounts_no_sender__aa6bf8_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profile_user',
            old_name='accounts_pr_user_id_97e401_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profile_can_post',
            old_name='accounts_pr_can_pos_58a68b_idx',
        ),
        migrations.RenameIndex(
            model_name='profile',
            new_name='profile_permission_req',
            old_name='accounts_pr_permiss_a6acd6_idx',
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_unread_recent'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read', 'created_at'], name='notif_cleanup'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notif_created_at'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['can_post', 'permission_requested'], name='profile_permissions'),
        ),
        migrations.AddIndex(
            model_name='profile',
            index=models.Index(fields=['permission_requested', 'can_post'], name='profile_pending_perms'),
        ),
    ]
