"""
Django settings for blog project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import sys
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Cargar variables de entorno desde .env
load_dotenv(os.path.join(BASE_DIR, ".env"))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "False").lower() in ("true", "1", "t")

ALLOWED_HOSTS_FROM_ENV = os.environ.get("ALLOWED_HOSTS")

if ALLOWED_HOSTS_FROM_ENV:
    ALLOWED_HOSTS = ALLOWED_HOSTS_FROM_ENV.split(",")
else:
    ALLOWED_HOSTS = ["localhost", "127.0.0.1"]

# Confiar en el origen para peticiones seguras a través del proxy
CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host not in ["localhost", "127.0.0.1"]]


# Application definition

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    # Apps de terceros
    "django_ckeditor_5",
    "taggit",
    "rest_framework",
    "turnstile",
    # Mis apps
    "posts",
    "accounts",
]

# Claves de Cloudflare Turnstile
TURNSTILE_SITE_KEY = os.environ.get("TURNSTILE_SITE_KEY")
TURNSTILE_SECRET_KEY = os.environ.get("TURNSTILE_SECRET_KEY")

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "blog.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "blog.configuraciones.context_processors.notifications_context",
            ],
        },
    },
]

WSGI_APPLICATION = "blog.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "es-ar"

TIME_ZONE = "America/Argentina/Buenos_Aires"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "/static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "guardian.backends.ObjectPermissionBackend",
)

DATA_UPLOAD_MAX_MEMORY_SIZE = 8388608  # 8 MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 8388608  # 8 MB

# LOGGING = {
#     "version": 1,
#     "disable_existing_loggers": False,
#     "formatters": {
#         "verbose": {
#             "format": "{levelname} {asctime} {module} {message}",
#             "style": "{",
#         },
#     },
#     "handlers": {
#         "file": {
#             "level": "INFO",
#             "class": "logging.FileHandler",
#             "filename": os.path.join(BASE_DIR, "logs", "admin.log"),
#             "formatter": "verbose",
#         },
#     },
#     "loggers": {
#         "django.request": {
#             "handlers": ["file"],
#             "level": "INFO",
#             "propagate": True,
#         },
#     },
# }

JAZZMIN_SETTINGS = {
    # Títulos e Iconos
    "site_title": "Mi Admin",
    "site_header": "Mi Proyecto",
    "site_brand": "Proyecto Final",
    "welcome_sign": "Bienvenido a Mi Proyecto",
    "copyright": "Mi Proyecto Ltd.",
    "search_model": "auth.User",
    # --- Menú Superior ---
    "topmenu_links": [
        # Ver Sitio
        {"name": "Ver Sitio", "url": "/", "new_window": True},
        # Modelos principales en el menú superior
        {"model": "auth.User"},
        {"model": "posts.Post"},
        # Enlace externo
        {
            "name": "Soporte Jazzmin",
            "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": False,
        },
    ],
    # --- Menú de Usuario ---
    "usermenu_links": [
        {
            "name": "Soporte Jazzmin",
            "url": "https://github.com/farridav/django-jazzmin/issues",
            "new_window": False,
        },
        {"model": "auth.user"},
    ],
    # --- Menú Lateral ---
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["auth", "posts", "accounts"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "posts.Post": "fas fa-newspaper",
        "posts.Comment": "fas fa-comments",
        "accounts.Profile": "fas fa-id-card",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    # --- UI Customizer (Selector de Temas) ---
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "related_modal_active": True,
}

# Configuración de la interfaz de usuario de Jazzmin (modo oscuro)
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": False,
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "button_classes": {
        "primary": "btn-outline-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success",
    },
}


CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading",
            "|",
            "bold",
            "italic",
            "link",
            "bulletedList",
            "numberedList",
            "blockQuote",
            "|",
            "undo",
            "redo",
        ],
    }
}

# --- Test Settings ---
# Detect if running 'test' command
TESTING = 'test' in sys.argv

if TESTING:
    SECRET_KEY = "a-dummy-secret-key-for-testing"
    DEBUG = False
    PASSWORD_HASHERS = [
        "django.contrib.auth.hashers.MD5PasswordHasher",
    ]
    TURNSTILE_SITE_KEY = None
    TURNSTILE_SECRET_KEY = None
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": ":memory:",
        }
    }
    EMAIL_BACKEND = "django.core.mail.backends.locmem.EmailBackend"


# --- Production/Development Specific Settings ---
if not TESTING:
    if DEBUG:
        # --- Development Settings ---
        EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

    else:
        # --- Production Settings ---
        # Security
        # SECURE_SSL_REDIRECT = True
        # SESSION_COOKIE_SECURE = True
        # CSRF_COOKIE_SECURE = True
        # SECURE_HSTS_SECONDS = 31536000  # 1 year
        # SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        # SECURE_HSTS_PRELOAD = True

        # Confiar en la cabecera X-Forwarded-Proto de Nginx
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

        # Static files
        MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")
        STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

        # Email (configure your actual email backend here)
        # EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
        # EMAIL_HOST = 'smtp.example.com'
        # EMAIL_PORT = 587
        # EMAIL_USE_TLS = True
        # EMAIL_HOST_USER = os.environ.get('EMAIL_USER')
        # EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PASS')