name: Django CI

on:
  push:
    branches: [ "main", "master" ] # Cambia esto según tu rama principal
  pull_request:
    branches: [ "main", "master" ] # Y también aquí

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t django-app .

    - name: Run Django Tests
      run: docker run django-app python manage.py test

